/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Wed Apr 29 23:34:58 EDT 2015
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist TableEnumOrId
 */
public enum TableEnumOrIdEnum {

    // Case
    CASE("Case"),
    // Lead
    LEAD("Lead"),
    // Opportunity
    OPPORTUNITY("Opportunity"),
    // Solution
    SOLUTION("Solution");

    final String value;

    private TableEnumOrIdEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static TableEnumOrIdEnum fromValue(String value) {
        for (TableEnumOrIdEnum e : TableEnumOrIdEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}